language: c

stages:
    - build_and_test
    - deploy

matrix:
    include:
        # Ubuntu Xenial
        - stage: build_and_test
          os: linux
          sudo: false
          dist: xenial
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-xenial-7
                  packages:
                      - attr
                      - cmake
                      - clang-7
                      - libattr1-dev
                      - libfuse-dev
                      - lsb-release
                      - uuid-dev
                  update: true
          env:
              - C_COMPILER=clang-7
              - CXX_COMPILER=clang++-7
              - BUILD=cmake
          script: contrib/travis/xenial.sh

        # OpenSUSE 12.3 + Tumbleweed Repo
        - stage: build_and_test
          os: linux
          sudo: true
          dist: xenial
          addons:
              apt:
                  update: false
          services: docker
          env:
            - C_COMPILER=clang-7
            - CXX_COMPILER=clang++-7
            - BUILD=cmake
            - DOCKER_IMAGE=saltstack/opensuse-12.3-minimal
          script: contrib/travis/suse.sh

        # # CentOS 7
        # - stage: build_and_test
        #   os: linux
        #   sudo: true
        #   dist: xenial
        #   addons:
        #       apt:
        #           update: false
        #   services: docker
        #   env:
        #     - C_COMPILER=clang
        #     - CXX_COMPILER=clang++
        #     - BUILD=cmake
        #     - DOCKER_IMAGE=centos
        #   script: contrib/travis/centos7.sh

        # macOS 10.13 CMake
        - stage: build_and_test
          os: osx
          osx_image: xcode10.1
          sudo: false
          addons:
              homebrew:
                  packages:
                      - cmake
                      - llvm@7
                      - mysql
                      - ossp-uuid
                      - sqlite3
                      - truncate
                  update: true
          env:
              - C_COMPILER=clang
              - CXX_COMPILER=clang++
              - BUILD=cmake
              - FORMULAE=llvm@7
          script: contrib/travis/osx.sh

        # macOS 10.13 make
        - stage: build_and_test
          os: osx
          osx_image: xcode10.1
          sudo: false
          addons:
              homebrew:
                  packages:
                      - cmake
                      - llvm@7
                      - mysql
                      - ossp-uuid
                      - sqlite3
                      - truncate
                  update: true
          env:
              - C_COMPILER=clang
              - CXX_COMPILER=clang++
              - BUILD=make
              - FORMULAE=llvm@7
          script: contrib/travis/osx.sh

        # Deploy cron jobs
        - stage: deploy
          os: linux
          sudo: false
          dist: xenial
          addons:
              apt:
                  packages:
                      - bsd-mailx
          deploy:
              provider: script
              skip-cleanup: true
              script: bash contrib/travis/deploy.sh gufi.tar.gz
              on:
                  branch: master
                  condition: ("${TRAVIS_EVENT_TYPE}" = "cron")
                  tags: false

        # manually triggered deploy
        - stage: deploy
          os: linux
          sudo: false
          dist: xenial
          addons:
              apt:
                  packages:
                      - bsd-mailx
          deploy:
              provider: script
              skip-cleanup: true
              script: bash contrib/travis/deploy.sh gufi.tar.gz
              on:
                  all_branches: true
                  condition: ("${TRAVIS_EVENT_TYPE}" = "api")
                  tags: false
