language: c
sudo: false

branches:
    only:
        - gufi_find

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - cmake
            - libsqlite3-dev
            - libfuse-dev

script:
    - make
    - test/runtests
    - test/verifyknowntree
    - test/googletest/test
