# This file is part of GUFI, which is part of MarFS, which is released
# under the BSD license.
#
#
# Copyright (c) 2017, Los Alamos National Security (LANS), LLC
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# From Los Alamos National Security, LLC:
# LA-CC-15-039
#
# Copyright (c) 2017, Los Alamos National Security, LLC All rights reserved.
# Copyright 2017. Los Alamos National Security, LLC. This software was produced
# under U.S. Government contract DE-AC52-06NA25396 for Los Alamos National
# Laboratory (LANL), which is operated by Los Alamos National Security, LLC for
# the U.S. Department of Energy. The U.S. Government has rights to use,
# reproduce, and distribute this software.  NEITHER THE GOVERNMENT NOR LOS
# ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR
# ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.  If software is
# modified to produce derivative works, such modified software should be
# clearly marked, so as not to confuse it with the version available from
# LANL.
#
# THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.



name: GitHub Actions

on: [push]

env:
  CC: clang
  CXX: clang++

jobs:
  Linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        img: [ "centos:7", "centos:8", "rockylinux:8", "ubuntu:20.04" ]
      fail-fast: true
    container:
      image: ${{ matrix.img }}
    steps:
    - uses: actions/checkout@v3

    - name: CentOS 7 Prerequisites
      if:  matrix.img == 'centos:7'
      run: contrib/CI/centos7.sh

    - name: CentOS 8 Prerequisites
      if:  matrix.img == 'centos:8'
      run: contrib/CI/centos8.sh

    - name: Rocky Linux Prerequisites
      if:  matrix.img == 'rockylinux:8'
      run: contrib/CI/rocky.sh

    - name: Ubuntu 20.04 Prerequisites
      if:  matrix.img == 'ubuntu:20.04'
      run: contrib/CI/ubuntu.sh

    - name: Configure CMake
      run:  cmake -B ${{github.workspace}}/build -DDEP_BUILD_THREADS=2 -DDEP_USE_JEMALLOC=Off -DENABLE_SUDO_TESTS=On

    - name: Build
      run:  cmake --build ${{github.workspace}}/build -j

    - name: Test
      run:  |
            cd ${{github.workspace}}/build
            ctest --output-on-failure

  Older_CMake:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
    - uses: actions/checkout@v3

    - name: CentOS 7 Prerequisites
      run:  contrib/CI/centos7.sh

    - name: Install CMake 3.1.0
      run:  contrib/CI/cmake3.1.0.sh

    - name: Check CMake Version
      run:  cmake --version

    - name: Configure CMake
      run: |
           mkdir -p build
           cd build
           cmake .. -DDEP_BUILD_THREADS=2 -DDEP_USE_JEMALLOC=Off -DENABLE_SUDO_TESTS=On

    - name: Build
      run: |
           cd build
           make -j

    - name: Test
      run: |
           cd build
           ctest --output-on-failure

  RPM:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
    - uses: actions/checkout@v3

    - name: CentOS 7 Prerequisites
      run:  contrib/CI/centos7.sh

    - name: Configure CMake
      run:  |
            mkdir -p build
            cd build
            cmake .. -DDEP_BUILD_THREADS=2 -DDEP_USE_JEMALLOC=Off

    - name: Test
      run:  build/contrib/CI/generic_rpm.sh

  Client:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
    - uses: actions/checkout@v3

    - name: CentOS 7 Prerequisites
      run:  contrib/CI/centos7.sh

    - name: Configure CMake
      run: |
           mkdir -p build
           cd build
           cmake .. -DDEP_BUILD_THREADS=2 -DDEP_USE_JEMALLOC=Off -DCLIENT=On

    - name: Test
      run:  build/contrib/CI/rpms.sh

  Documentation:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Ubuntu:20.04 Prerequisites
      run:  sudo contrib/CI/ubuntu.sh

    - name: Install LaTeX
      run:  sudo apt -y install texlive-latex-extra imagemagick

    - name: Configure CMake
      run:  cmake -B ${{github.workspace}}/build -DLATEX_BUILD=On

    - name: Build PDFs
      run:  cmake --build ${{github.workspace}}/build --target gufi_user gufi_administrator gufi_developer

  macOS:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3

    - name: macOS 11 Prerequisites
      run:  contrib/CI/osx.sh

    - name: Configure CMake
      run: |
           source ~/.bash_profile
           cmake -B ${{github.workspace}}/build -DDEP_BUILD_THREADS=2 -DDEP_USE_JEMALLOC=Off -DENABLE_SUDO_TESTS=On

    - name: Build
      run: |
           source ~/.bash_profile
           cmake --build ${{github.workspace}}/build -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
